### PR TITLE
LUTECE-2164 : Add a CSRF token to indexation actions

### PR DESCRIPTION
**Pull request by rzara**
Add a way to unregister an indexer, to allow adding and removing
a test indexer.

### CODE REVIEW

**Comment by jonenst** [comment]
Was there a specific problem with having a dummy indexer during the tests ? I'm just thinking because we should be careful when adding methods to the public API just for tests.

**Comment by rzara** [comment]
The test would alter the global state of the system.
Furthermore, the new method should be used on plugin uninstall to remove registered indexers, which is not currently done, but was out of scope of this JIRA

**Comment by jonenst** [comment]
The global state is already very altered during unit tests.. I don't think it would have been a problem to have a dummy indexer and the standard one. But as you said there might be a usage for this new unregister function so let's add it.

Regarding "history.go(-1)" vs an href to a page, usually we do this when there are several pages linking to the current page. In this case it looks like an error. Is that why you changed it ?

**Comment by rzara** [comment]
I changed the history.go(-1) so that a CSRF token is regenerated.

**Comment by jonenst** [comment]
Ha yes I understand. Thanks !

**Pull request merged**
