### PR TITLE
LUTECE-2078 : use extension points in included ant files

### PR DESCRIPTION
**Pull request by rzara**
That way, targets in them do not depend on unknown targets from build.xml

### CODE REVIEW

**Comment by jonenst** [comment]
Is it ok to declare the same extension point multiple times ..? Can't find anything in the docs, and I'm no ant expert :(
Maybe they should have different names db_core_init_ep_FILE and we declare multiple extensionOf in build.xml ?

**Comment by rzara** [comment]
It is OK. for instance, here are some ant files:
build.xml:
```
<project name="top">
<import file="imported1.xml"/>
<import file="imported2.xml"/>
<target name="extending" extensionOf="myExtention"></target>
</project>
```
imported1.xml:
```
<project name="imported1">
<extension-point name="myExtention" />
<target name="imported1" depends="myExtention"></target>
</project>
```
and imported2.xml:
```
<project name="imported2">
<extension-point name="myExtention" />
<target name="imported2" depends="myExtention"></target>
</project>
```

then
```
C:\Data\Boulot\test\antExtPoint>ant imported1
Buildfile: C:\Data\Boulot\test\antExtPoint\build.xml

extending:

myExtention:

imported1:

BUILD SUCCESSFUL
Total time: 0 seconds

C:\Data\Boulot\test\antExtPoint>ant imported2
Buildfile: C:\Data\Boulot\test\antExtPoint\build.xml

extending:

myExtention:

imported2:

BUILD SUCCESSFUL
Total time: 0 seconds
```

If you put two extension-points with the same name in the same file, there is an error.
With imported1.xml:
```
<project name="imported1">
<extension-point name="myExtention" />
<extension-point name="myExtention" />
<target name="imported1" depends="myExtention"></target>
</project>
```

you get
```
C:\Data\Boulot\test\antExtPoint>ant imported1
Buildfile: C:\Data\Boulot\test\antExtPoint\build.xml

BUILD FAILED
C:\Data\Boulot\test\antExtPoint\build.xml:2: The following error occurred while executing this line:
C:\Data\Boulot\test\antExtPoint\imported1.xml:3: Duplicate target 'myExtention'

Total time: 0 seconds
```

**Comment by jonenst** [comment]
Merged, thanks !

**Comment by jonenst** [comment]
For info, with old parent poms, this crashes the build (tested with fr.paris.lutece.plugins:lutece-plugins-pom:3.7)
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.2:run (default-cli) on project plugin-adminauthenticationdatabase: An Ant BuildException has occured: The following error occurred while executing this line:
[ERROR] /home/jon/lutece_full_svn/portal/trunk/plugins/authentication/plugin-adminauthenticationdatabase/target/lutece/WEB-INF/sql/build.xml:73: Unexpected attribute "extensionOf"
```

**Pull request merged**
