### PR TITLE
Internationalize flatpickr macros

### PR DESCRIPTION
**Pull request by markpatton**
This pr demonstrates how flatpickr macros can be used to internationalize date and time picking. The key ability of flatpickr is to show a localized form of a date or time to the user while sending the dates and times to the server in a different format. A complication is that the date format expected by the Lutece backend depends on the configured locale of the client. The picker must have that server side expectation (see the property lutece.format.date.short) hard coded. In contrast, the time format expected by the server is always the same. Another complication is the need to handle the administrative site and the public site differently. Administrative web pages have a locale or language FreeMarker variable set. This can be passed to the date and time picker macros. But that variable is not available on the public site. On the public site, the choice of localization needs to happen dynamically on the client side. These new macros handle that case by using moment.locale() when a language is not provided.

Known issues:
  - Due to load order and timing issues the flatpickr localization needs to be loaded in a script tag early on. But for the public site, the locale is not provided as as FreeMarker variable. Therefore macros needs to load all possible localization they will be required to handle when being used by the public site. For this demonstration, only English and French are a concern. English is provided by default, so French is always loaded for the public site. This is clearly not ideal if you wanted to handle many languages. But the files could be bundled together, or the timing issues could be figured out and the localization loaded dynamically with jQuery.getScript or similar methods.

### CODE REVIEW

**Comment by seboo** [comment]
Hi,
thanks for the PR !
we are going to study the different points.

here are some feedbacks:
- moment.js is not yet supplied with the core, this should be studied, we think instead to use the function [(new Intl.DateTimeFormat ()). resolvedOptions (). locale] to retrieve the locale, it looks like well supported by different browsers.
- we will add more attributes to * flatPicker macros to match the attributes available for a date type input (including mindate and maxdate ...)
- about the preloading of the scripts, the problem had been spotted and solved (normally!)
- we are going to correct the problem of calling the language file for the default case of "en".

About the main problem: we should be able to retrieve the list of default date-time format patterns by language. We have not yet found a function which would allow the pattern to be retrieved for the current language. There are a few tricks, but we are more likely to rely on a specific script that would contain an array of values, while waiting for something better.

The Jira LUTECE-2374 issue was opened on this.
Bests

**Comment by markpatton** [comment]
> * moment.js is not yet supplied with the core, this should be studied, we think instead to use the function [(new Intl.DateTimeFormat ()). resolvedOptions (). locale] to retrieve the locale, it looks like well supported by different browsers.

That look like a better solution than moment, but I do see the moment library in lutece-core. Look at ./webapp/js/admin/style/bootstrap4/material-kit/moment-with-locales.min.js.

> * we will add more attributes to * flatPicker macros to match the attributes available for a date type input (including mindate and maxdate ...)
> * about the preloading of the scripts, the problem had been spotted and solved (normally!)
> * we are going to correct the problem of calling the language file for the default case of "en".

Good. My main concern is that the macros work for both the admin and public site. The public site wont be able to pass language as a parameter to the macro.

> About the main problem: we should be able to retrieve the list of default date-time format patterns by language. We have not yet found a function which would allow the pattern to be retrieved for the current language. There are a few tricks, but we are more likely to rely on a specific script that would contain an array of values, while waiting for something better.

Yes. That seems expedient.

> The Jira LUTECE-2374 issue was opened on this.

Awesome! Will check it out.

> Bests

**Comment by seboo** [comment]
Hi
> I do see the moment library in lutece-core. Look at ./webapp/js/admin/style/bootstrap4/material-kit/moment-with-locales.min.js.

That script is only included for bootstrap4-materialkit template yet. We try to let  *datePicker macros  independent of the rendering template engine choice.

> My main concern is that the macros work for both the admin and public site. The public site wont be able to pass language as a parameter to the macro.

In theory, macros are reserved for the back office. In practice, yes, they can be used (and are used) in front office, and this can lead to compatibility problems, we must refine our thinking on this point.
I think that * datePicker macros are not necessarily affected by this problem, regardless of whether the language is available or not, since we can use the current browser language to display the date in the local format and then send an ISO format to the server. 


I will leave this PR open while waiting for the JIRA LUTECE-2374 fix (I hope within a few days, if our load plan allows us)
bests

**Comment by markpatton** [comment]
Note I've also updated the date time picker macro in the same way. It's needed by the forms plugin. Also, the current version also could not work because the date time format is specified incorrectly.

**Comment by markpatton** [comment]
Note I've also updated the date time picker macro in the same way. It's needed by the forms plugin. In any case, it could not have worked because the date time format is specified incorrectly. The server wants a MYSQL timestamp format.

**Comment by markpatton** [comment]
One additional issue with these macros being used by the public site, the public sites often don't seem to load bootstrap-flatpickr.min.css. One solution would be to just always load this where the js library is loaded in these macros.

**Comment by seboo** [comment]
Hi,
Sorry for the delay.
The LUTECE-2374 branch, that should respond to this need, is ready to be merged !
(we'll do it tomorrow i think).

Features : 
- new macros names are independent of the JS library (next step will be to propose HTML5 implementation)
- Dates, Times and ranges are managed
- the lang is set by default, according to the lang used by freemarker to render the template
- the locale is the default locale of the same lang in the browser's configuration
- the display format depends on this locale (the default format list can be overriden)
- Dates are sent to the server with ISO format by default
- macro is avaiblable in FO 
- input macro has new attributes according to datePicker macros (as minDate and maxDate)
- old macros are present in the backport macro files for compatibility

thank you for your contribution, i will close your Pull Request next week if you are ok.

**Comment by markpatton** [comment]
I'm looking at  LUTECE-2374 and it seems like a good approach. I think it's good to close. We will test after the merge and report any problems.

**Comment by seboo** [comment]
Hi,
Sorry for the delay.
The LUTECE-2374 branch, that should respond to this need, is ready to be merged !
(we'll do it tomorrow i think).

Features : 
- new macros names are independent of the JS library (next step will be to propose HTML5 implementation)
- Dates, Times and ranges are managed
- the lang is set by default, according to the lang used by freemarker to render the template
- the locale is the default locale of the same lang in the browser's configuration
- the display format depends on this locale (the default format list can be overriden)
- Dates are sent to the server with ISO format by default
- macro is avaiblable in FO 
- input macro has new attributes according to datePicker macros (as minDate and maxDate)
- old macros are present in the backport macro files for compatibility

thank you for your contribution, i will close your Pull Request next week if you are ok.

**Comment by seboo** [comment]
LUTECE-2374 branch merged

**Pull request closed without merging**
