### PR TITLE
LUTECE-2089 : add a CSRF protection token to the login form

### PR DESCRIPTION
**Pull request by rzara**

### CODE REVIEW

**Comment by jonenst** [comment]
CSRF attacks on login forms is not as dangerous as other CSRF attacks. Is this worth it ? At least it should be part of a greater plan to tackle all csrf problems.

 @pierrelevy

**Comment by rzara** [comment]
First one in a series (I have grepped form tags).
The login form is less critic but you can imagine attack scenarii.

**Comment by jonenst** [comment]
Thanks, merged !

**Comment by jonenst** [comment]
Hmm, this broke the demo site http://dev.lutece.paris.fr/site-demo/, which shows an admin login form on its front page..

**Comment by rzara** [comment]
Well fixing the demo site should not be very difficult... Is the front page an HTML portlet ?

**Comment by jonenst** [comment]
Yes it's using an html portlet.

**Comment by rzara** [comment]
Can be fixed by adding the following js in the portlet with the login form:

    $.ajax("jsp/admin/AdminLogin.jsp").done(function(data) {
    var token = /name="token"\s+value="(.*)"/.exec(data)[1];
    var input = document.createElement("input");
    input.type="hidden";
    input.name="token";
    input.value=token;
    $("form").prepend(input);
    });

**Comment by jonenst** [comment]
Haha it's quite funny that we will "hack" our own csrf protection mechanism.

**Comment by rzara** [comment]
It works because it's on the same domain. Maybe we lack enforcement of "POST" http method

**Comment by jonenst** [comment]
Yeah, it's like an auto xss attack :)

Also, I confirm that a get to https://dev.lutece.paris.fr/site-demo/jsp/admin/DoAdminLogin.jsp?token=6b239857-6038-44f1-9ece-44c971aab23a&access_code=admin&password=adminadmin will log you in.

Also, after the login, the token is forwarded to next page. It should be excluded like the password and user field... This comes from the weird design decision of having the parameters to the next page be real parameters of the admin page, instead of more simply being quoted/escaped.

**Comment by jonenst** [comment]
Doing a get on "jsp/admin/AdminLogin.jsp" kills the session... So adding it to the front page of the site will be annoying.
The fact that a simple get on AdminLogin.jsp has side effects could be used to make some kind of denial of service. Also, being able to trigger a forced reauthentication might be used in other scenarios.

I'll put a link to the backoffice login form. If no one complains about it, then it solves the problem

**Pull request merged**
