### PR TITLE
LUTECE-2021 : Improvements around back office passwords

### PR DESCRIPTION
**Pull request by rzara**
Some improvements around BO passwords:
- expire default passwords
- deactivate sample accounts
- require longer password
- better inform the user of password size requirements
- Use a secure RNG to generate passwords

### CODE REVIEW

**Comment by AlexandreClose** [comment]
OpenJDK8 doesn't support PBKDF2WithHmacSHA512 algorithm yet.

    03/11/16 17:35:48 ERROR [http-nio-8080-exec-6] lutece.error - java.security.NoSuchAlgorithmException: PBKDF2WITHHMACSHA512 MessageDigest not available
    java.lang.IllegalArgumentException: java.security.NoSuchAlgorithmException: PBKDF2WITHHMACSHA512 MessageDigest not available

Another algotithm should be used if PBKDF2WithHmacSHA512 isn't found for keeping Lutece compatible with OpenJDK.

**Comment by jonenst** [comment]
We will have to see about expiring the default passwords. I'm not sure if this will actually prevent sites in production from using the default password, as people running those sites don't usually use ant, instead they they get a dump from someone running in a test environment where the password is the default password.

**Comment by jonenst** [comment]
pushed a rebased version at https://github.com/lutece-platform/lutece-core/tree/rzara-LUTECE-2021
We need to make  aria-describedby work with EJO's new freemarker macros

**Comment by rzara** [comment]
The integrator will use the ant script initially, and will be asked to change the default password when testing/configuring. So I still think this will reduce the risk.

**Comment by jonenst** [comment]
This was merged in 4d01bc0129334204bbb7abe4
Thanks !

**Pull request closed without merging**
